name: ppcinemas
description: "A proof-of-concept theater app designed for mobile devices built using Flutter."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.7.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^14.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - images/combo.png
    - images/drink.png
    - images/popcorn-large.png
    - images/popcorn-small.png
    - images/qr-code.png
    - images/movies/1917.jpg
    - images/movies/ambulancia.jpg
    - images/movies/dolittle.jpg
    - images/movies/gato-con-botas2.jpg
    - images/movies/grinch.jpg
    - images/movies/hobbsshaw.jpg